Bug: 1947293 Add managed provisioning network size validation
openshift/cluster-baremetal-operator pull request #164
Opened 2021-06-16 22:29 UTC by squidboylan

Validate that managed ipv6 provisioning networks are no larger than a
/64 due to a dnsmasq limitation, also add some relevant documentation.

2021-06-17 06:04 UTC, asalkeld requested changes

2021-06-17 06:04 UTC, asalkeld commented on api/v1alpha1/provisioning_validation.go
> +
extra new line that lint might not like

2021-06-17 06:04 UTC, asalkeld commented on api/v1alpha1/provisioning_validation.go
> +	if cidrSize < 64 && provisioningCIDR.IP.To4() == nil && provisioningCIDR.IP.To16() != nil && provisioningNetworkMode == ProvisioningNetworkManaged {
provisioningNetworkMode is undefined in this function

2021-06-17 15:40 UTC, squidboylan commented
/retest

2021-06-18 17:31 UTC, squidboylan commented
/retest

2021-06-22 23:48 UTC, asalkeld commented
@squidboylan you probably need to do a "make generate"

2021-06-23 23:05 UTC, squidboylan commented
> @squidboylan you probably need to do a "make generate"

thanks I was confused as to what was happening.

2021-06-25 02:28 UTC, asalkeld commented
/retest

2021-06-30 00:31 UTC, asalkeld reviewed
/lgtm

2021-07-02 15:34 UTC, sadasu commented
/approve

2021-07-03 00:18 UTC, merged