Stop linting when building the image
openshift/cluster-baremetal-operator pull request #343
Opened 2023-06-13 18:50 UTC by honza

When we build the image, the code has already been through code review, and CI.  Everything has been generated, and linted, and addressed.  At the build stage, we just want to compile the binary.

Furthermore, the golangci-lint program seems to require attention every time we upgrade Go in the builder.  This breaks the build, and we have to do emergency upgrades to get it unstuck.

2023-09-12 10:14 UTC, honza commented
/retest

2023-09-12 19:54 UTC, honza commented
/remove-lifecycle stale

2023-11-13 08:13 UTC, elfosardo requested changes

2023-11-13 08:13 UTC, elfosardo commented on Makefile
>  # Run against the configured Kubernetes cluster in ~/.kube/config
remove lint from here and remove L114

2023-11-13 12:37 UTC, honza commented on Makefile
>  # Run against the configured Kubernetes cluster in ~/.kube/config
Done

2023-11-13 12:53 UTC, dtantsur commented
/retitle NO-ISSUE: Stop linting when building the image
/lgtm

2023-11-13 12:54 UTC, dtantsur commented
/retest-required

2023-11-14 09:44 UTC, elfosardo commented
/label acknowledge-critical-fixes-only

2023-11-14 09:47 UTC, merged