[release-4.16] OCPBUGS-32304: Run metal3 containers as specific users and groups
openshift/cluster-baremetal-operator pull request #418
Opened 2024-05-21 14:50 UTC by MahnoorAsghar

This is a cherry-pick of #417

2024-05-21 14:51 UTC, MahnoorAsghar commented
/jira refresh

2024-05-21 15:00 UTC, MahnoorAsghar commented
/jira refresh

2024-05-21 15:01 UTC, MahnoorAsghar commented
/jira refresh

2024-05-22 16:43 UTC, MahnoorAsghar commented
/retest

2024-05-22 16:47 UTC, MahnoorAsghar commented
/test e2e-metal-sdn-assisted

2024-05-23 07:08 UTC, dtantsur commented
/approve
/label backport-risk-assessed

2024-05-23 07:35 UTC, MahnoorAsghar commented
/test e2e-metal-ipi-upgrade-ovn-ipv6

2024-05-23 07:37 UTC, MahnoorAsghar commented
/test ?

2024-05-28 09:52 UTC, MahnoorAsghar commented
/test e2e-metal-ipi-upgrade-ovn-ipv6

2024-05-28 09:55 UTC, MahnoorAsghar commented
/test ?

2024-05-28 09:57 UTC, MahnoorAsghar commented
/test e2e-metal-sdn-assisted

2024-05-28 12:04 UTC, MahnoorAsghar commented
/pj-rehearse max

2024-05-29 10:28 UTC, MahnoorAsghar commented
Just realized that I can't simply rebase this PR off the master branch because this is a cherry pick PR for the release-4.16 branch. (Was rebasing in efforts to resolve the failing e2e-metal-ipi-upgrade-ovn-ipv6 branch, will revert the rebase after checking job results)

2024-05-29 12:28 UTC, elfosardo requested changes

2024-05-29 12:28 UTC, elfosardo commented on .ci-operator.yaml
> +  tag: rhel-9-release-golang-1.21-openshift-4.17
let's not bump the images versions

2024-05-29 12:28 UTC, elfosardo commented on Dockerfile
> +FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.17 AS builder
ditto and below too

2024-05-29 14:04 UTC, elfosardo commented
/test govet

2024-05-29 14:59 UTC, MahnoorAsghar commented
/test e2e-metal-ipi-ovn-virtualmedia

2024-05-30 08:18 UTC, MahnoorAsghar commented
/test e2e-metal-ipi-bm

2024-05-30 08:29 UTC, MahnoorAsghar commented
/retest-required

2024-05-30 08:32 UTC, elfosardo commented
/lgtm

2024-06-03 08:27 UTC, MahnoorAsghar commented
The e2e-metal-ipi-upgrade-ovn-ipv6 job is perma-failing for PRs targeting the release branches. I have opened a story in Jira to address this issue. Since this is an optional test and this bug is a release blocker, I would override this job on this PR.

2024-06-03 08:36 UTC, elfosardo commented
/override ci/prow/e2e-metal-ipi-upgrade-ovn-ipv6

2024-06-03 15:19 UTC, jadhaj commented
/label cherry-pick-approved

2024-06-03 15:22 UTC, merged